Carriers.Mvc/Controllers/RatingController.cs
using AutoMapper;
using Carriers.Domain.Entities;
using Carriers.Domain.Interfaces;
using Carriers.Domain.Interfaces.Repositories;
using Carriers.Mvc.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Carriers.Mvc.Controllers
{
    public class RatingController : Controller
    {
        private readonly IRatingRepository _ratingRepository;
        private readonly ICarrierRepository _carrierRepository;
        private readonly IUserRepository _userRepository;

        public RatingController(IRatingRepository ratingRepository, ICarrierRepository carrierRepository, IUserRepository userRepository)
        {
            _ratingRepository = ratingRepository;
            _carrierRepository = carrierRepository;
            _userRepository = userRepository;
        }

        public ActionResult Index()
        {
            var carriers = _carrierRepository.GetAll();
            var user = (User)Session["User"];

            if (user == null)
                return RedirectToAction("Login", "Account");

            foreach (var item in carriers)
            {
                var rating = _ratingRepository.GetRatingBy(user.Id, item.Id);
                if (rating != null)
                    item.AvaliadaPeloUsuario = true;
            }

            var carriersVm = Mapper.Map<IEnumerable<Carrier>, IEnumerable<CarrierVm>>(carriers);
            return View(carriersVm);
        }

        public ActionResult Create(int id)
        {
            var user = (User)Session["User"];
            var carrier = _carrierRepository.GetById(id);
            var ratingVm = new RatingVm { IdCarrier = carrier.Id, IdUser = user.Id };

            return View("~/Views/Rating/Create.cshtml", ratingVm);
        }

        [HttpPost]
        public ActionResult Create(RatingVm ratingViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var rating = Mapper.Map<RatingVm, Rating>(ratingViewModel);


                    rating.Carrier =_carrierRepository.GetById(ratingViewModel.IdCarrier);
                   
                    rating.User = (User)Session["User"]; 

                    _ratingRepository.Add(rating);

                }
                catch (DbEntityValidationException ex)
                {
                    StringBuilder sb = new StringBuilder();

                    foreach (var failure in ex.EntityValidationErrors)
                    {
                        sb.AppendFormat("{0} failed validation\n", failure.Entry.Entity.GetType());
                        foreach (var error in failure.ValidationErrors)
                        {
                            sb.AppendFormat("- {0} : {1}", error.PropertyName, error.ErrorMessage);
                            sb.AppendLine();
                        }
                    }
                }

                return RedirectToAction("Index");
            }

            return View(ratingViewModel);
        }

        public ActionResult Edit(int id)
        {
            var rating = _ratingRepository.GetById(id);
            var ratingVm = Mapper.Map<Rating, RatingVm>(rating);

            return View(ratingVm);
        }

        [HttpPost]
        public ActionResult Edit(RatingVm ratingViewModel)
        {
            if (ModelState.IsValid)
            {
                var rating = Mapper.Map<RatingVm, Rating>(ratingViewModel);
                _ratingRepository.Update(rating);

                return RedirectToAction("Index");
            }

            return View(ratingViewModel);
        }

        public ActionResult Details(int id)
        {
            var rating = _ratingRepository.GetById(id);
            var ratingVm = Mapper.Map<Rating, RatingVm>(rating);

            return View(ratingVm);
        }

        public ActionResult Delete(int id)
        {
            var rating = _ratingRepository.GetById(id);
            var ratingVm = Mapper.Map<Rating, RatingVm>(rating);

            return View(ratingVm);
        }

        [HttpPost]
        public ActionResult Delete(RatingVm carrierViewModel)
        {

            //var carrier = Mapper.Map<CarrierVm, Carrier>(carrierViewModel);
            var rating = _ratingRepository.GetById(carrierViewModel.Id);
            _ratingRepository.Remove(rating);

            return RedirectToAction("Index");

        }
    }
}

Carriers.Mvc/Views/Rating/Create.cshtml
@model Carriers.Mvc.ViewModels.RatingVm
@using Carriers.Domain.Enuns
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Rating", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.HiddenFor(model => model.IdCarrier)
    @Html.HiddenFor(model => model.IdUser)

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Avaliar Transportadora</h4>
        <hr />
        <div class="form-group">
            @Html.Label("Agilidade na Entrega", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.AgilidadeNaEntrega, Enum.GetNames(typeof(ERatingCarrier)).Select(e => new SelectListItem { Text = e }), "Selecione...")
                @Html.ValidationMessageFor(model => model.AgilidadeNaEntrega, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Cuidado com Mercadoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CuidadoComMercadoria, Enum.GetNames(typeof(ERatingCarrier)).Select(e => new SelectListItem { Text = e }), "Selecione...")
                @Html.ValidationMessageFor(model => model.CuidadoComMercadoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Transparência", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Transparencia, Enum.GetNames(typeof(ERatingCarrier)).Select(e => new SelectListItem { Text = e }), "Selecione...")
                @Html.ValidationMessageFor(model => model.Transparencia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Comunicação", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.BoaComunicacao, Enum.GetNames(typeof(ERatingCarrier)).Select(e => new SelectListItem { Text = e }), "Selecione...")
                @Html.ValidationMessageFor(model => model.BoaComunicacao, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Carriers.Mvc/Views/Rating/Index.cshtml
@model IEnumerable<Carriers.Mvc.ViewModels.CarrierVm>

@{
    ViewBag.Title = "Index";
}

<h2>Avaliar Transportadoras</h2>
@if (!Model.Any())
{
    <p>
        Não possui transportadoras cadastradas para avaliar.
    </p>
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RazaoSocial)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RazaoSocial)
            </td>
            <td>
                @if (!item.AvaliadaPeloUsuario)
                {
                    @Html.ActionLink("Avaliar", "Create", new { id = item.Id })
                }
                else
                {
                    <p>Já foi avaliada por você</p>
                }


            </td>
        </tr>
    }

</table>