Carriers.Mvc/Controllers/CarrierController.cs
using AutoMapper;
using Carriers.Domain.Entities;
using Carriers.Domain.Interfaces;
using Carriers.Mvc.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Carriers.Mvc.Controllers
{
    public class CarrierController : Controller
    {
        private readonly ICarrierRepository _carrierRepository;

        public CarrierController(ICarrierRepository carrierRepository)
        {
            _carrierRepository = carrierRepository;
        }

        public ActionResult Index()
        {

            var carriers = _carrierRepository.GetAll();
            var carriersVm = Mapper.Map<IEnumerable<Carrier>, IEnumerable<CarrierVm>>(carriers);
            return View(carriersVm);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CarrierVm carrierViewModel)
        {
            if (ModelState.IsValid)
            {
                var carrier = Mapper.Map<CarrierVm, Carrier>(carrierViewModel);
                _carrierRepository.Add(carrier);

                return RedirectToAction("Index");
            }

            return View(carrierViewModel);
        }

        public ActionResult Edit(int id)
        {
            var carrier = _carrierRepository.GetById(id);
            var carriersVm = Mapper.Map<Carrier, CarrierVm>(carrier);

            return View(carriersVm);
        }

        [HttpPost]
        public ActionResult Edit(CarrierVm carrierViewModel)
        {
            if (ModelState.IsValid)
            {
                var carrier = Mapper.Map<CarrierVm, Carrier>(carrierViewModel);
                _carrierRepository.Update(carrier);

                return RedirectToAction("Index");
            }

            return View(carrierViewModel);
        }

        public ActionResult Details(int id)
        {
            var carrier = _carrierRepository.GetById(id);
            var carriersVm = Mapper.Map<Carrier, CarrierVm>(carrier);

            return View(carriersVm);
        }

        public ActionResult Delete(int id)
        {
            var carrier = _carrierRepository.GetById(id);
            var carriersVm = Mapper.Map<Carrier, CarrierVm>(carrier);

            return View(carriersVm);
        }

        [HttpPost]
        public ActionResult Delete(CarrierVm carrierViewModel)
        {

            //var carrier = Mapper.Map<CarrierVm, Carrier>(carrierViewModel);
            var carrier = _carrierRepository.GetById(carrierViewModel.Id);
            _carrierRepository.Remove(carrier);

            return RedirectToAction("Index");

        }
    }
}

Carriers.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Carriers", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Session["User"] == null)
                    {
                        <li>@Html.ActionLink("Transportadoras", "Index", "Carrier")</li>
                    }
                    <li>@Html.ActionLink("Avaliar Transportadora", "Login", "Account")</li>

                </ul>
                @if (Session["User"] != null)
                {
                    <ul class="nav navbar-nav" style="float:right">
                        <li>@Html.ActionLink("Sair", "Logout", "Account")</li>
                    </ul>
                }

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/cdn-jquery")
    @Scripts.Render("~/bundles/cdn-jquery-mask")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>